version: '2'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog_a
      - blog_b
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 100M
        reservations:
          cpus: '0.10'
          memory: 10M

  blog_a:
    build: blog-a/ 
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.10'
          memory: 70M
        reservations:
          cpus: '0.01'
          memory: 10M 
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com, google.aws.com, www.mini.com
      - VIRTUL_PORT=80


  blog_b:
    build: blog-b/ 
    # image로 가능
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.10'
          memory: 70M
        reservations:
          cpus: '0.01'
          memory: 10M 
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=google.aws.com, aws.google.com
      - VIRTUL_PORT=80