version: '2'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 100M
        reservations:
          cpus: '0.10'
          memory: 10M

  blog:
    # build: ../../docker_file/httpd
    image: minicrane/blog-a:0.1.0 
    deploy:
      mode: replicated
      replicas: 20 # https://docs.docker.com/compose/compose-file/deploy/#replicas  복제 개수
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.10'
          memory: 70M
        reservations:
          cpus: '0.01'
          memory: 10M 
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com
      - VIRTUAL_PORT=80
